### PR TITLE
Minor changes in the build_and_upload script

### PR DESCRIPTION
**Pull request by tchapi**
With the introduction of a SPECIFIC flag, I've bubbled the changes in the build_and_upload script that hopefully is used by some people to make the firmware :)

### CODE REVIEW

**Comment by mickeyboss123** [comment]
☆Building Error☆
Building firmware (en) for mighty_one
scons: Reading SConscript files ...

scons: warning: Ignoring missing SConscript 'build/mighty_one/SConscript.mightyboard'
File "/Users/mickey/MightyBoardFirmware/firmware/SConstruct", line 11, in <module>
scons: done reading SConscript files.
scons: Building targets ...
scons: `.' is up to date.
scons: done building targets.

**Comment by tchapi** [comment]
mickeyboss123 afaik these commits do not change anything to SConstruct that has been modified beforehand. Works fine on my side, the file `build/mighty_one/SConscript.mightyboard` gets created correctly. Problem of rights, maybe ?

**Comment by tchapi** [comment]
@aleonard any chances this PR goes through at some point ? ;)

**Comment by andyjon** [comment]
Hi all,

when I use ./firmware/build_and_upload.sh to budding this, but something fail..
- Building firmware (en) for mighty_one () ... Success
  find: ./build: No such file or directory
  Failure

is there anyone have been this situation?

**Comment by tchapi** [comment]
Have you tried to create the directory yourself before building ? It might just be a rights issue :

```
mkdir ./firmware/build
```

**Pull request merged**
